### ISSUE TITLE
UI - minor issue: answer div size ? should we set div height?

### ISSUE THREAD

**Issue by andreiskandar** [andreiskandar/quiz-app#28]

**Comment by andreiskandar** [comment]
![Screen Shot 2020-09-20 at 8 39 55 PM](https://user-images.githubusercontent.com/56459037/93731357-7295e300-fb81-11ea-88bd-7533c718ac23.png)

**Comment by andreiskandar** [comment]
![Screen Shot 2020-09-20 at 8 40 43 PM](https://user-images.githubusercontent.com/56459037/93731387-8f321b00-fb81-11ea-9e9c-af8b7b161102.png)

**Comment by HatHeadNinja** [comment]
Keep as fixed as possible for demo
