### ISSUE TITLE
3 random queries

### ISSUE THREAD

**Issue by HatHeadNinja** [andreiskandar/quiz-app#46]
SELECT * FROM quizzes WHERE public = true AND active = true ORDER BY RANDOM() LIMIT 3;

**Comment by AndrewRLloyd88** [comment]
Solved!

**Comment by HatHeadNinja** [comment]
I am hacking the 3 random quizzes, since there are only 4 complete quiz sets at the moment.
Started out making a smart randomizer:

1. query the db for quizzes which are public and active
2. set the floor for the randomizer to highest id of public&&active quizzes
3. check to make sure the selected number is not a dupe
4. push it to an array and repeat step 2-4 two more times
5. return array of random IDs

Was getting complicated and some errors, so stepped back to simplify.  To increase the number of random quizzes, we just have to open the code and add the quiz ID to the array in the function:

1. randomly pick 3 numbers from the valid quiz IDs in the array
2. return array of random IDs
